FROM icinga/icinga2:2

# import check_elastic_stack nagios plugin and icinga2 conf
# USER root
COPY --chmod=755 check_elastic_stack.sh /usr/lib/nagios/plugins/check_elastic_stack
COPY check_elastic_stack.conf /data/etc/icinga2/conf.d/check_elastic_stack.conf
# COPY check_elastic_stack.conf /etc/icinga2/conf.d/check_elastic_stack.conf
# RUN chmod +x /usr/lib/nagios/plugins/check_elastic_stack
# USER icinga

CMD ["icinga2", "daemon", "-C"]