name: check_elastic_stack unit tests

# events that trigger jobs
on:
  push:
    branches: [dev]

# groups a set of actions that will be executed
# jobs run in parallel by default, unless a job "needs" another job
jobs:
  test_icinga2:
    # needs: some_other_job
    runs-on: ubuntu-latest

    # container:
    #   image: node:18
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1

    # each step can import from a pre-existing action on GitHub, or can be a new action from scratch
    # each step builds on the previous one
    # steps run sequentially
    steps:
    # this is normally always present and ensure your app's repo itself is loaded
    - uses: actions/checkout@v2

    - name: Build icinga2 test environment
      run: |
        docker build -t 9xeb/check_elastic_stack/icinga2:test -f docker/icinga2/Dockerfile.test .

    - name: Test icinga2 configurations
      run:
        docker run --rm 9xeb/check_elastic_stack/icinga2:test
    # - name: 
    #   uses: actions/setup-java@v1
    #   with:
    #     java_version: 1.8
    
    # - name: Grant execute permissions for gradlew
    #   run: chmod +x gradlew

    # - name: Build with Gradle
    #   run: ./gradlew build
